version: '3.1'

services:
  mongo:
    image: mongo:4.0.4
    restart: always
    ports: 
        - 27017:27017
    volumes: 
        - $HOME/Workspace/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example